name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      - name: Run rubocop with reviewdog
        uses: reviewdog/action-script@v1
        with:
          script: bundle exec rubocop --format=json
          tool_name: rubocop
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          filter_mode: file
          github_token: ${{ secrets.GITHUB_TOKEN }}
